### ISSUE TITLE
"Music" library is hardcoded

### ISSUE THREAD

**Issue by dragoshenron** [jasmith79/apple_playlist_plex_importer#2]
First, thanks for this piece of software!

I'm moving my iTunes library from MacOSX to PMS on QNAP. After fiddle around to install python3, pip and git, I was able to run the your script.

I've notice that "Music" library is hardcoded. I didn't have it so the script throw an error.
https://github.com/jasmith79/apple_playlist_plex_importer/blob/9240c1d3af0794b78ea2ee675cdcb2d585d2f5c8/plex_importer/plex.py#L38

Hence, I've created a new library called "Music" which I'll rename afterwards.
Do you think would be useful to have the library name as parameter?

**Comment by jasmith79** [comment]
Glad it was able to help you!

I will have to experiment a bit to see if it works with non-default library sections, but glancing at [the relevant section of the plexapi](https://github.com/pkkid/python-plexapi/blob/master/plexapi/library.py) it seems like it should work as long as the library section has the right type tag.

I should have time to look at it this weekend hopefully.

**Comment by dragoshenron** [comment]
Yes, you help me a lot because any other tentative to import songs from iTunes failed, no matter what.

My library is definitely of type Music when was created so the tags should be correct.

If I may ask something OT, it would be possible to import from the .xml also the rating (number of stars)?

**Comment by jasmith79** [comment]
Ok this should be fixed by [b892e29e](https://github.com/jasmith79/apple_playlist_plex_importer/commit/b892e29e5990820d65801f5a4e8dee9e92a2a48b). Go ahead and update by following the [installation instructions in the README](https://github.com/jasmith79/apple_playlist_plex_importer) again. This commit adds a `--section` flag that defaults to 'Music', see `--help` for details. As for the ratings, that is a property of the underlying tracks, not the playlists, so this would not be an appropriate tool to do that with. It is certainly possible to create something like that using the plex api (the data from iTunes is there in the xml file for sure), but I probably won't be doing it.

If you want to try your hand at it, the relevant class in the plex api is probably audio.Track, found [here](https://github.com/pkkid/python-plexapi/blob/master/plexapi/audio.py).

Please let me know if this resolves your issue with the Section so I can close this.

**Comment by dragoshenron** [comment]
Thanks jasmith79.

All solved, you can close the issue.
BTW, I've solved the rating issue by creating 5 different playslists, each for star (1-star playlist, 2-star playlise, ...) Quick and dirty (and working).

Cheers,
Alex

**Comment by jasmith79** [comment]
Glad everything is working for you!

**Comment by jasmith79** [comment]
@dragoshenron did you ever find this? Could probably be helpful for you https://github.com/meisnate12/Plex-Meta-Manager
